#! /usr/bin/env python3
# Author: WHo
# Version: 1.0
# Description: This script will demo how to ITERATE through a
# sequence (str/tuple/list/dict/set) using an ITERATOR for loop

heroes = ['iron man', 'deadpool', 'batman', 'hulk', 'wonder women']

# ITERATE through the heros LIST using an ITERATOR loop

for hero in heroes:
    print(hero, end="\n")

# ITERNATE through the list and MODIFY the values using an
# ITERATOR loop plus and index counter

idx = 0 
for hero in heroes:
    print(hero.upper())
    heroes[idx] = hero.upper()
    idx += 1
print("Heroes=", heroes)


# ITERNATE through the list and MODIFY the values using an
# ITERATOR loop plus built in enumerate() function


for (idx, hero) in enumerate(heroes, start=0):
    print(hero.title())
    heroes[idx] = hero.upper()
print("Heroes=", heroes)